/* The following code was generated by JFlex 1.7.0 tweaked for IntelliJ platform */

/*
 * Copyright 2014 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package se.clau.yang.lexer;
import com.intellij.psi.tree.IElementType;
import com.intellij.lexer.FlexLexer;
import se.clau.yang.psi.YangTypes;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>_YangLexer.flex</tt>
 */
public class _YangLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int VALUE_MODE = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   * Chosen bits are [8, 6, 7]
   * Total runtime size is 1040 bytes
   */
  public static int ZZ_CMAP(int ch) {
    return ZZ_CMAP_A[ZZ_CMAP_Y[ZZ_CMAP_Z[ch>>13]|((ch>>7)&0x3f)]|(ch&0x7f)];
  }

  /* The ZZ_CMAP_Z table has 136 entries */
  static final char ZZ_CMAP_Z[] = zzUnpackCMap(
    "\1\0\207\100");

  /* The ZZ_CMAP_Y table has 128 entries */
  static final char ZZ_CMAP_Y[] = zzUnpackCMap(
    "\1\0\177\200");

  /* The ZZ_CMAP_A table has 256 entries */
  static final char ZZ_CMAP_A[] = zzUnpackCMap(
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\7\1\0\1\11\4\0\1\10\2\0\1\5\1\15\1\0\1\36"+
    "\1\12\1\4\12\12\1\13\1\14\5\0\32\12\1\0\1\6\2\0\1\45\1\0\1\20\1\33\1\40\1"+
    "\43\1\31\1\42\1\27\1\41\1\37\1\12\1\47\1\25\1\24\1\21\1\35\1\44\1\51\1\26"+
    "\1\34\1\32\1\30\1\46\1\52\1\23\1\22\1\50\1\16\1\0\1\17\202\0");

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\2\3\1\4\1\5\1\6\1\7"+
    "\25\3\1\10\2\1\1\10\1\11\1\12\2\0\56\3"+
    "\2\0\1\10\2\0\2\2\2\0\23\3\1\13\11\3"+
    "\1\14\26\3\1\15\1\3\1\0\1\2\11\3\1\16"+
    "\2\3\1\17\1\3\1\20\10\3\1\21\1\22\2\3"+
    "\1\23\1\24\13\3\1\25\11\3\1\26\4\3\1\27"+
    "\15\3\1\30\5\3\1\31\13\3\1\32\17\3\1\33"+
    "\1\34\10\3\1\35\2\3\1\36\1\3\1\37\3\3"+
    "\1\40\5\3\1\41\2\3\1\42\1\3\1\43\4\3"+
    "\1\44\1\45\7\3\1\46\2\3\1\47\17\3\1\50"+
    "\4\3\1\51\3\3\1\52\1\3\1\53\1\3\1\54"+
    "\1\55\1\3\1\56\2\3\1\57\11\3\1\60\1\3"+
    "\1\61\10\3\1\62\4\3\1\63\1\64\1\65\3\3"+
    "\1\66\2\3\1\67\1\70\2\3\1\71\3\3\1\72"+
    "\3\3\1\73\2\3\1\74\11\3\1\75\1\3\1\76"+
    "\1\77\4\3\1\100\10\3\1\101\1\102\1\103\1\104"+
    "\1\105\4\3\1\106\1\3\1\107\1\3\1\110\1\111"+
    "\4\3\1\112\1\113";

  private static int [] zzUnpackAction() {
    int [] result = new int[433];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\201\0\254\0\327\0\126\0\126"+
    "\0\126\0\126\0\u0102\0\u012d\0\u0158\0\u0183\0\u01ae\0\u01d9"+
    "\0\u0204\0\u022f\0\u025a\0\u0285\0\u02b0\0\u02db\0\u0306\0\u0331"+
    "\0\u035c\0\u0387\0\u03b2\0\u03dd\0\u0408\0\u0433\0\u045e\0\u0489"+
    "\0\u04b4\0\u04df\0\u050a\0\126\0\126\0\u0535\0\u0560\0\u058b"+
    "\0\u05b6\0\u05e1\0\u060c\0\u0637\0\u0662\0\u068d\0\u06b8\0\u06e3"+
    "\0\u070e\0\u0739\0\u0764\0\u078f\0\u07ba\0\u07e5\0\u0810\0\u083b"+
    "\0\u0866\0\u0891\0\u08bc\0\u08e7\0\u0912\0\u093d\0\u0968\0\u0993"+
    "\0\u09be\0\u09e9\0\u0a14\0\u0a3f\0\u0a6a\0\u0a95\0\u0ac0\0\u0aeb"+
    "\0\u0b16\0\u0b41\0\u0b6c\0\u0b97\0\u0bc2\0\u0bed\0\u0c18\0\u0c43"+
    "\0\u0c6e\0\u0c99\0\u0cc4\0\u0cef\0\u0d1a\0\u04b4\0\u0d45\0\126"+
    "\0\u04df\0\u0d70\0\u0d9b\0\126\0\u0dc6\0\u0df1\0\u0e1c\0\u0e47"+
    "\0\u0e72\0\u0e9d\0\u0ec8\0\u0ef3\0\u0f1e\0\u0f49\0\u0f74\0\u0f9f"+
    "\0\u0fca\0\u0ff5\0\u1020\0\u104b\0\u1076\0\u10a1\0\u10cc\0\u10f7"+
    "\0\u1122\0\327\0\u114d\0\u1178\0\u11a3\0\u11ce\0\u11f9\0\u1224"+
    "\0\u124f\0\u127a\0\u12a5\0\327\0\u12d0\0\u12fb\0\u1326\0\u1351"+
    "\0\u137c\0\u13a7\0\u13d2\0\u13fd\0\u1428\0\u1453\0\u147e\0\u14a9"+
    "\0\u14d4\0\u14ff\0\u152a\0\u1555\0\u1580\0\u15ab\0\u15d6\0\u1601"+
    "\0\u162c\0\u1657\0\327\0\u1682\0\u16ad\0\u0dc6\0\u16d8\0\u1703"+
    "\0\u172e\0\u1759\0\u1784\0\u17af\0\u17da\0\u1805\0\u1830\0\327"+
    "\0\u185b\0\u1886\0\u18b1\0\u18dc\0\327\0\u1907\0\u1932\0\u195d"+
    "\0\u1988\0\u19b3\0\u19de\0\u1a09\0\u1a34\0\327\0\327\0\u1a5f"+
    "\0\u1a8a\0\u1ab5\0\327\0\u1ae0\0\u1b0b\0\u1b36\0\u1b61\0\u1b8c"+
    "\0\u1bb7\0\u1be2\0\u1c0d\0\u1c38\0\u1c63\0\u1c8e\0\327\0\u1cb9"+
    "\0\u1ce4\0\u1d0f\0\u1d3a\0\u1d65\0\u1d90\0\u1dbb\0\u1de6\0\u1e11"+
    "\0\327\0\u1e3c\0\u1e67\0\u1e92\0\u1ebd\0\327\0\u1ee8\0\u1f13"+
    "\0\u1f3e\0\u1f69\0\u1f94\0\u1fbf\0\u1fea\0\u2015\0\u2040\0\u206b"+
    "\0\u2096\0\u20c1\0\u20ec\0\327\0\u2117\0\u2142\0\u216d\0\u2198"+
    "\0\u21c3\0\327\0\u21ee\0\u2219\0\u2244\0\u226f\0\u229a\0\u22c5"+
    "\0\u22f0\0\u231b\0\u2346\0\u2371\0\u239c\0\327\0\u23c7\0\u23f2"+
    "\0\u241d\0\u2448\0\u2473\0\u249e\0\u24c9\0\u24f4\0\u251f\0\u254a"+
    "\0\u2575\0\u25a0\0\u25cb\0\u25f6\0\u2621\0\327\0\327\0\u264c"+
    "\0\u2677\0\u26a2\0\u26cd\0\u26f8\0\u2723\0\u274e\0\u2779\0\327"+
    "\0\u27a4\0\u27cf\0\327\0\u27fa\0\327\0\u2825\0\u2850\0\u287b"+
    "\0\327\0\u28a6\0\u28d1\0\u28fc\0\u2927\0\u2952\0\327\0\u297d"+
    "\0\u29a8\0\327\0\u29d3\0\327\0\u29fe\0\u2a29\0\u2a54\0\u2a7f"+
    "\0\327\0\327\0\u2aaa\0\u2ad5\0\u2b00\0\u2b2b\0\u2b56\0\u2b81"+
    "\0\u2bac\0\327\0\u2bd7\0\u2c02\0\327\0\u2c2d\0\u2c58\0\u2c83"+
    "\0\u2cae\0\u2cd9\0\u2d04\0\u2d2f\0\u2d5a\0\u2d85\0\u2db0\0\u2ddb"+
    "\0\u2e06\0\u2e31\0\u2e5c\0\u2e87\0\327\0\u2eb2\0\u2edd\0\u2f08"+
    "\0\u2f33\0\327\0\u2f5e\0\u2f89\0\u2fb4\0\327\0\u2fdf\0\327"+
    "\0\u300a\0\327\0\327\0\u3035\0\327\0\u3060\0\u308b\0\327"+
    "\0\u30b6\0\u30e1\0\u310c\0\u3137\0\u3162\0\u318d\0\u31b8\0\u31e3"+
    "\0\u320e\0\u3239\0\u3264\0\327\0\u328f\0\u32ba\0\u32e5\0\u3310"+
    "\0\u333b\0\u3366\0\u3391\0\u33bc\0\327\0\u33e7\0\u3412\0\u343d"+
    "\0\u3468\0\327\0\327\0\327\0\u3493\0\u34be\0\u34e9\0\327"+
    "\0\u3514\0\u353f\0\327\0\327\0\u356a\0\u3595\0\327\0\u35c0"+
    "\0\u35eb\0\u3616\0\327\0\u3641\0\u366c\0\u3697\0\327\0\u36c2"+
    "\0\u36ed\0\327\0\u3718\0\u3743\0\u376e\0\u3799\0\u37c4\0\u37ef"+
    "\0\u381a\0\u3845\0\u3870\0\327\0\u389b\0\327\0\327\0\u38c6"+
    "\0\u38f1\0\u391c\0\u3947\0\327\0\u3972\0\u399d\0\u39c8\0\u39f3"+
    "\0\u3a1e\0\u3a49\0\u3a74\0\u3a9f\0\327\0\327\0\327\0\327"+
    "\0\327\0\u3aca\0\u3af5\0\u3b20\0\u3b4b\0\327\0\u3b76\0\327"+
    "\0\u3ba1\0\327\0\327\0\u3bcc\0\u3bf7\0\u3c22\0\u3c4d\0\327"+
    "\0\327";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[433];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\3\4\1\5\2\3\1\4\2\3\1\6\1\3"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\6"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\6\1\30\1\31\1\6\1\32\1\33"+
    "\1\34\1\6\1\35\1\36\2\6\1\37\1\3\3\4"+
    "\1\40\2\3\1\4\1\41\1\42\1\43\1\3\1\44"+
    "\1\10\1\45\1\3\33\43\54\0\3\4\3\0\1\4"+
    "\47\0\1\46\1\47\4\0\2\6\4\0\33\6\12\0"+
    "\2\6\4\0\33\6\12\0\2\6\4\0\1\6\1\50"+
    "\4\6\1\51\1\6\1\52\22\6\12\0\2\6\4\0"+
    "\1\53\14\6\1\54\15\6\12\0\2\6\4\0\1\55"+
    "\16\6\1\56\13\6\12\0\2\6\4\0\1\57\7\6"+
    "\1\60\4\6\1\61\1\6\1\62\13\6\12\0\2\6"+
    "\4\0\11\6\1\63\5\6\1\64\13\6\12\0\2\6"+
    "\4\0\1\65\10\6\1\66\12\6\1\67\6\6\12\0"+
    "\2\6\4\0\6\6\1\70\24\6\12\0\2\6\4\0"+
    "\1\6\1\71\12\6\1\72\16\6\12\0\2\6\4\0"+
    "\1\6\1\73\1\6\1\74\2\6\1\75\24\6\12\0"+
    "\2\6\4\0\2\6\1\76\30\6\12\0\2\6\4\0"+
    "\1\77\10\6\1\100\5\6\1\101\13\6\12\0\2\6"+
    "\4\0\10\6\1\102\1\6\1\103\20\6\12\0\2\6"+
    "\4\0\6\6\1\104\1\6\1\105\22\6\12\0\2\6"+
    "\4\0\1\6\1\106\2\6\1\107\15\6\1\110\1\111"+
    "\7\6\12\0\2\6\4\0\1\112\14\6\1\113\3\6"+
    "\1\114\11\6\12\0\2\6\4\0\6\6\1\115\2\6"+
    "\1\116\21\6\12\0\2\6\4\0\11\6\1\117\21\6"+
    "\12\0\2\6\4\0\1\120\5\6\1\121\6\6\1\122"+
    "\15\6\12\0\2\6\4\0\1\123\32\6\12\0\2\6"+
    "\4\0\11\6\1\124\21\6\12\0\2\6\4\0\21\6"+
    "\1\125\11\6\4\0\1\46\1\47\4\0\2\43\4\0"+
    "\33\43\6\126\1\127\1\126\1\130\42\126\6\131\1\132"+
    "\2\131\1\130\41\131\12\0\2\43\4\0\33\43\1\46"+
    "\1\133\1\134\50\46\5\135\1\136\45\135\12\0\2\6"+
    "\4\0\2\6\1\137\30\6\12\0\2\6\4\0\7\6"+
    "\1\140\23\6\12\0\2\6\4\0\7\6\1\141\23\6"+
    "\12\0\2\6\4\0\4\6\1\142\26\6\12\0\2\6"+
    "\4\0\12\6\1\143\20\6\12\0\2\6\4\0\1\6"+
    "\1\144\31\6\12\0\2\6\4\0\1\6\1\145\31\6"+
    "\12\0\2\6\4\0\1\6\1\146\1\6\1\147\27\6"+
    "\12\0\2\6\4\0\14\6\1\150\16\6\12\0\2\6"+
    "\4\0\23\6\1\151\7\6\12\0\2\6\4\0\1\6"+
    "\1\152\31\6\12\0\2\6\4\0\1\153\1\154\31\6"+
    "\12\0\2\6\4\0\14\6\1\155\16\6\12\0\2\6"+
    "\4\0\1\6\1\156\31\6\12\0\2\6\4\0\22\6"+
    "\1\157\3\6\1\160\2\6\1\161\1\6\12\0\2\6"+
    "\4\0\20\6\1\162\12\6\12\0\2\6\4\0\15\6"+
    "\1\163\15\6\12\0\2\6\4\0\17\6\1\164\13\6"+
    "\12\0\2\6\4\0\11\6\1\165\21\6\12\0\2\6"+
    "\4\0\10\6\1\166\22\6\12\0\2\6\4\0\12\6"+
    "\1\167\20\6\12\0\2\6\4\0\6\6\1\170\24\6"+
    "\12\0\2\6\4\0\24\6\1\171\6\6\12\0\2\6"+
    "\4\0\14\6\1\172\16\6\12\0\2\6\4\0\5\6"+
    "\1\173\25\6\12\0\2\6\4\0\12\6\1\174\20\6"+
    "\12\0\2\6\4\0\13\6\1\175\17\6\12\0\2\6"+
    "\4\0\1\176\32\6\12\0\2\6\4\0\7\6\1\177"+
    "\13\6\1\200\7\6\12\0\2\6\4\0\12\6\1\201"+
    "\20\6\12\0\2\6\4\0\20\6\1\202\3\6\1\203"+
    "\6\6\12\0\2\6\4\0\24\6\1\204\6\6\12\0"+
    "\2\6\4\0\16\6\1\205\14\6\12\0\2\6\4\0"+
    "\11\6\1\206\21\6\12\0\2\6\4\0\14\6\1\207"+
    "\16\6\12\0\2\6\4\0\1\6\1\210\31\6\12\0"+
    "\2\6\4\0\15\6\1\211\15\6\12\0\2\6\4\0"+
    "\1\212\32\6\12\0\2\6\4\0\1\213\32\6\12\0"+
    "\2\6\4\0\14\6\1\214\5\6\1\215\3\6\1\216"+
    "\4\6\12\0\2\6\4\0\12\6\1\217\20\6\12\0"+
    "\2\6\4\0\11\6\1\220\21\6\12\0\2\6\4\0"+
    "\14\6\1\221\16\6\12\0\2\6\4\0\5\6\1\222"+
    "\25\6\12\0\2\6\4\0\2\6\1\223\30\6\12\0"+
    "\2\6\4\0\11\6\1\224\21\6\7\126\1\0\43\126"+
    "\7\131\1\0\43\131\2\0\1\134\50\0\5\135\1\225"+
    "\51\135\1\226\1\225\45\135\12\0\2\6\4\0\3\6"+
    "\1\227\27\6\12\0\2\6\4\0\10\6\1\230\22\6"+
    "\12\0\2\6\4\0\4\6\1\231\26\6\12\0\2\6"+
    "\4\0\11\6\1\232\21\6\12\0\2\6\4\0\17\6"+
    "\1\233\13\6\12\0\2\6\4\0\7\6\1\234\23\6"+
    "\12\0\2\6\4\0\16\6\1\235\14\6\12\0\2\6"+
    "\4\0\23\6\1\236\7\6\12\0\2\6\4\0\16\6"+
    "\1\237\14\6\12\0\2\6\4\0\12\6\1\240\20\6"+
    "\12\0\2\6\4\0\10\6\1\241\22\6\12\0\2\6"+
    "\4\0\16\6\1\242\14\6\12\0\2\6\4\0\22\6"+
    "\1\243\10\6\12\0\2\6\4\0\7\6\1\244\23\6"+
    "\12\0\2\6\4\0\12\6\1\245\20\6\12\0\2\6"+
    "\4\0\7\6\1\246\23\6\12\0\2\6\4\0\11\6"+
    "\1\247\5\6\1\250\13\6\12\0\2\6\4\0\17\6"+
    "\1\251\13\6\12\0\2\6\4\0\10\6\1\252\22\6"+
    "\12\0\2\6\4\0\10\6\1\253\22\6\12\0\2\6"+
    "\4\0\12\6\1\254\16\6\1\255\1\6\12\0\2\6"+
    "\4\0\14\6\1\256\16\6\12\0\2\6\4\0\4\6"+
    "\1\257\26\6\12\0\2\6\4\0\11\6\1\260\21\6"+
    "\12\0\2\6\4\0\15\6\1\261\15\6\12\0\2\6"+
    "\4\0\11\6\1\262\21\6\12\0\2\6\4\0\11\6"+
    "\1\263\21\6\12\0\2\6\4\0\15\6\1\264\15\6"+
    "\12\0\2\6\4\0\4\6\1\265\26\6\12\0\2\6"+
    "\4\0\12\6\1\266\20\6\12\0\2\6\4\0\1\267"+
    "\32\6\12\0\2\6\4\0\11\6\1\270\21\6\12\0"+
    "\2\6\4\0\24\6\1\271\6\6\12\0\2\6\4\0"+
    "\5\6\1\272\25\6\12\0\2\6\4\0\10\6\1\273"+
    "\22\6\12\0\2\6\4\0\15\6\1\274\15\6\12\0"+
    "\2\6\4\0\22\6\1\275\10\6\12\0\2\6\4\0"+
    "\1\6\1\276\31\6\12\0\2\6\4\0\11\6\1\277"+
    "\21\6\12\0\2\6\4\0\12\6\1\300\7\6\1\301"+
    "\10\6\12\0\2\6\4\0\17\6\1\302\13\6\12\0"+
    "\2\6\4\0\20\6\1\303\12\6\12\0\2\6\4\0"+
    "\12\6\1\304\20\6\12\0\2\6\4\0\20\6\1\305"+
    "\12\6\12\0\2\6\4\0\1\306\32\6\12\0\2\6"+
    "\4\0\17\6\1\307\13\6\12\0\2\6\4\0\12\6"+
    "\1\310\6\6\1\311\11\6\12\0\2\6\4\0\14\6"+
    "\1\312\5\6\1\313\10\6\12\0\2\6\4\0\17\6"+
    "\1\314\13\6\12\0\2\6\4\0\10\6\1\315\22\6"+
    "\12\0\2\6\4\0\1\6\1\316\31\6\4\135\1\134"+
    "\1\225\45\135\12\0\2\6\4\0\4\6\1\317\26\6"+
    "\12\0\2\6\4\0\4\6\1\320\26\6\12\0\2\6"+
    "\4\0\11\6\1\321\21\6\12\0\2\6\4\0\14\6"+
    "\1\322\16\6\12\0\2\6\4\0\22\6\1\323\10\6"+
    "\12\0\2\6\4\0\16\6\1\324\14\6\12\0\2\6"+
    "\4\0\11\6\1\325\21\6\12\0\2\6\4\0\1\326"+
    "\32\6\12\0\2\6\4\0\11\6\1\327\21\6\12\0"+
    "\2\6\4\0\5\6\1\330\25\6\12\0\2\6\4\0"+
    "\11\6\1\331\21\6\12\0\2\6\4\0\16\6\1\332"+
    "\14\6\12\0\2\6\4\0\12\6\1\333\20\6\12\0"+
    "\2\6\4\0\11\6\1\334\21\6\12\0\2\6\4\0"+
    "\6\6\1\335\24\6\12\0\2\6\4\0\1\6\1\336"+
    "\31\6\12\0\2\6\4\0\14\6\1\337\16\6\12\0"+
    "\2\6\4\0\17\6\1\340\13\6\12\0\2\6\4\0"+
    "\24\6\1\341\6\6\12\0\2\6\4\0\14\6\1\342"+
    "\16\6\12\0\2\6\4\0\10\6\1\343\22\6\12\0"+
    "\2\6\4\0\1\6\1\344\31\6\12\0\2\6\4\0"+
    "\6\6\1\345\24\6\12\0\2\6\4\0\23\6\1\346"+
    "\7\6\12\0\2\6\4\0\1\6\1\347\31\6\12\0"+
    "\2\6\4\0\15\6\1\350\15\6\12\0\2\6\4\0"+
    "\10\6\1\351\22\6\12\0\2\6\4\0\1\6\1\352"+
    "\31\6\12\0\2\6\4\0\6\6\1\353\24\6\12\0"+
    "\2\6\4\0\10\6\1\354\22\6\12\0\2\6\4\0"+
    "\10\6\1\355\22\6\12\0\2\6\4\0\12\6\1\356"+
    "\20\6\12\0\2\6\4\0\6\6\1\357\24\6\12\0"+
    "\2\6\4\0\11\6\1\360\21\6\12\0\2\6\4\0"+
    "\12\6\1\361\20\6\12\0\2\6\4\0\1\362\32\6"+
    "\12\0\2\6\4\0\17\6\1\363\13\6\12\0\2\6"+
    "\4\0\20\6\1\364\12\6\12\0\2\6\4\0\12\6"+
    "\1\365\20\6\12\0\2\6\4\0\10\6\1\366\22\6"+
    "\12\0\2\6\4\0\6\6\1\367\24\6\12\0\2\6"+
    "\4\0\10\6\1\370\22\6\12\0\2\6\4\0\1\371"+
    "\32\6\12\0\2\6\4\0\11\6\1\372\21\6\12\0"+
    "\2\6\4\0\11\6\1\373\21\6\12\0\2\6\4\0"+
    "\17\6\1\374\13\6\12\0\2\6\4\0\12\6\1\375"+
    "\20\6\12\0\2\6\4\0\11\6\1\376\21\6\12\0"+
    "\2\6\4\0\5\6\1\377\25\6\12\0\2\6\4\0"+
    "\11\6\1\u0100\21\6\12\0\2\6\4\0\1\6\1\u0101"+
    "\31\6\12\0\2\6\4\0\24\6\1\u0102\6\6\12\0"+
    "\2\6\4\0\17\6\1\u0103\13\6\12\0\2\6\4\0"+
    "\26\6\1\u0104\4\6\12\0\2\6\4\0\5\6\1\u0105"+
    "\25\6\12\0\2\6\4\0\12\6\1\u0106\20\6\12\0"+
    "\2\6\4\0\5\6\1\u0107\25\6\12\0\2\6\4\0"+
    "\11\6\1\u0108\21\6\12\0\2\6\4\0\5\6\1\u0109"+
    "\25\6\12\0\2\6\4\0\5\6\1\u010a\25\6\12\0"+
    "\2\6\4\0\21\6\1\u010b\11\6\12\0\2\6\4\0"+
    "\11\6\1\u010c\21\6\12\0\2\6\4\0\11\6\1\u010d"+
    "\21\6\12\0\2\6\4\0\17\6\1\u010e\13\6\12\0"+
    "\2\6\4\0\6\6\1\u010f\24\6\12\0\2\6\4\0"+
    "\17\6\1\u0110\13\6\12\0\2\6\4\0\11\6\1\u0111"+
    "\21\6\12\0\2\6\4\0\14\6\1\u0112\16\6\12\0"+
    "\2\6\4\0\16\6\1\u0113\14\6\12\0\2\6\4\0"+
    "\11\6\1\u0114\21\6\12\0\2\6\4\0\7\6\1\u0115"+
    "\23\6\12\0\2\6\4\0\23\6\1\u0116\7\6\12\0"+
    "\2\6\4\0\14\6\1\u0117\16\6\12\0\2\6\4\0"+
    "\17\6\1\u0118\13\6\12\0\2\6\4\0\11\6\1\u0119"+
    "\21\6\12\0\2\6\4\0\12\6\1\u011a\20\6\12\0"+
    "\2\6\4\0\23\6\1\u011b\7\6\12\0\2\6\4\0"+
    "\12\6\1\u011c\20\6\12\0\2\6\4\0\1\u011d\32\6"+
    "\12\0\2\6\4\0\17\6\1\u011e\13\6\12\0\2\6"+
    "\4\0\17\6\1\u011f\1\u0120\12\6\12\0\2\6\4\0"+
    "\7\6\1\u0121\23\6\12\0\2\6\4\0\11\6\1\u0122"+
    "\21\6\12\0\2\6\4\0\17\6\1\u0123\13\6\12\0"+
    "\2\6\4\0\6\6\1\u0124\24\6\12\0\2\6\4\0"+
    "\17\6\1\u0125\13\6\12\0\2\6\4\0\5\6\1\u0126"+
    "\25\6\12\0\2\6\4\0\12\6\1\u0127\20\6\12\0"+
    "\2\6\4\0\6\6\1\u0128\24\6\12\0\2\6\4\0"+
    "\1\6\1\u0129\31\6\12\0\2\6\4\0\3\6\1\u012a"+
    "\27\6\12\0\2\6\4\0\17\6\1\u012b\13\6\12\0"+
    "\2\6\4\0\1\6\1\u012c\31\6\12\0\2\6\4\0"+
    "\12\6\1\u012d\20\6\12\0\2\6\4\0\1\u012e\32\6"+
    "\12\0\2\6\4\0\20\6\1\u012f\12\6\12\0\2\6"+
    "\4\0\11\6\1\u0130\21\6\12\0\2\6\4\0\11\6"+
    "\1\u0131\21\6\12\0\2\6\4\0\15\6\1\u0132\15\6"+
    "\12\0\2\6\4\0\11\6\1\u0133\21\6\12\0\2\6"+
    "\4\0\11\6\1\u0134\21\6\12\0\2\6\4\0\17\6"+
    "\1\u0135\13\6\12\0\2\6\4\0\1\6\1\u0136\31\6"+
    "\12\0\2\6\4\0\15\6\1\u0137\15\6\12\0\2\6"+
    "\4\0\11\6\1\u0138\21\6\12\0\2\6\4\0\1\6"+
    "\1\u0139\31\6\12\0\2\6\4\0\17\6\1\u013a\13\6"+
    "\12\0\2\6\4\0\1\u013b\3\6\1\u013c\26\6\12\0"+
    "\2\6\4\0\22\6\1\u013d\10\6\12\0\2\6\4\0"+
    "\14\6\1\u013e\16\6\12\0\2\6\4\0\10\6\1\u013f"+
    "\22\6\12\0\2\6\4\0\30\6\1\u0140\2\6\12\0"+
    "\2\6\4\0\23\6\1\u0141\7\6\12\0\2\6\4\0"+
    "\11\6\1\u0142\21\6\12\0\2\6\4\0\12\6\1\u0143"+
    "\20\6\12\0\2\6\4\0\12\6\1\u0144\20\6\12\0"+
    "\2\6\4\0\1\6\1\u0145\31\6\12\0\2\6\4\0"+
    "\12\6\1\u0146\20\6\12\0\2\6\4\0\15\6\1\u0147"+
    "\15\6\12\0\2\6\4\0\11\6\1\u0148\21\6\12\0"+
    "\2\6\4\0\24\6\1\u0149\6\6\12\0\2\6\4\0"+
    "\12\6\1\u014a\20\6\12\0\2\6\4\0\11\6\1\u014b"+
    "\5\6\1\u014c\13\6\12\0\2\6\4\0\1\6\1\u014d"+
    "\31\6\12\0\2\6\4\0\20\6\1\u014e\12\6\12\0"+
    "\2\6\4\0\15\6\1\u014f\15\6\12\0\2\6\4\0"+
    "\12\6\1\u0150\20\6\12\0\2\6\4\0\20\6\1\u0151"+
    "\12\6\12\0\2\6\4\0\1\u0152\32\6\12\0\2\6"+
    "\4\0\6\6\1\u0153\24\6\12\0\2\6\4\0\4\6"+
    "\1\u0154\26\6\12\0\2\6\4\0\6\6\1\u0155\24\6"+
    "\12\0\2\6\4\0\4\6\1\u0156\26\6\12\0\2\6"+
    "\4\0\4\6\1\u0157\26\6\12\0\2\6\4\0\14\6"+
    "\1\u0158\16\6\12\0\2\6\4\0\20\6\1\u0159\12\6"+
    "\12\0\2\6\4\0\1\6\1\u015a\31\6\12\0\2\6"+
    "\4\0\16\6\1\u015b\14\6\12\0\2\6\4\0\7\6"+
    "\1\u015c\23\6\12\0\2\6\4\0\15\6\1\u015d\15\6"+
    "\12\0\2\6\4\0\24\6\1\u015e\6\6\12\0\2\6"+
    "\4\0\11\6\1\u015f\21\6\12\0\2\6\4\0\16\6"+
    "\1\u0160\14\6\12\0\2\6\4\0\5\6\1\u0161\25\6"+
    "\12\0\2\6\4\0\1\u0162\32\6\12\0\2\6\4\0"+
    "\16\6\1\u0163\14\6\12\0\2\6\4\0\10\6\1\u0164"+
    "\22\6\12\0\2\6\4\0\2\6\1\u0165\30\6\12\0"+
    "\2\6\4\0\11\6\1\u0166\21\6\12\0\2\6\4\0"+
    "\1\6\1\u0167\31\6\12\0\2\6\4\0\12\6\1\u0168"+
    "\20\6\12\0\2\6\4\0\15\6\1\u0169\15\6\12\0"+
    "\2\6\4\0\11\6\1\u016a\21\6\12\0\2\6\4\0"+
    "\1\6\1\u016b\31\6\12\0\2\6\4\0\11\6\1\u016c"+
    "\21\6\12\0\2\6\4\0\12\6\1\u016d\20\6\12\0"+
    "\2\6\4\0\14\6\1\u016e\16\6\12\0\2\6\4\0"+
    "\11\6\1\u016f\21\6\12\0\2\6\4\0\2\6\1\u0170"+
    "\30\6\12\0\2\6\4\0\11\6\1\u0171\21\6\12\0"+
    "\2\6\4\0\11\6\1\u0172\21\6\12\0\2\6\4\0"+
    "\12\6\1\u0173\20\6\12\0\2\6\4\0\11\6\1\u0174"+
    "\21\6\12\0\2\6\4\0\16\6\1\u0175\14\6\12\0"+
    "\2\6\4\0\17\6\1\u0176\13\6\12\0\2\6\4\0"+
    "\1\6\1\u0177\31\6\12\0\2\6\4\0\24\6\1\u0178"+
    "\6\6\12\0\2\6\4\0\14\6\1\u0179\16\6\12\0"+
    "\2\6\4\0\12\6\1\u017a\20\6\12\0\2\6\4\0"+
    "\11\6\1\u017b\21\6\12\0\2\6\4\0\12\6\1\u017c"+
    "\20\6\12\0\2\6\4\0\13\6\1\u017d\17\6\12\0"+
    "\2\6\4\0\6\6\1\u017e\24\6\12\0\2\6\4\0"+
    "\6\6\1\u017f\24\6\12\0\2\6\4\0\16\6\1\u0180"+
    "\14\6\12\0\2\6\4\0\17\6\1\u0181\13\6\12\0"+
    "\2\6\4\0\1\6\1\u0182\31\6\12\0\2\6\4\0"+
    "\17\6\1\u0183\13\6\12\0\2\6\4\0\17\6\1\u0184"+
    "\13\6\12\0\2\6\4\0\1\6\1\u0185\31\6\12\0"+
    "\2\6\4\0\1\6\1\u0186\31\6\12\0\2\6\4\0"+
    "\1\6\1\u0187\31\6\12\0\2\6\4\0\23\6\1\u0188"+
    "\7\6\12\0\2\6\4\0\1\6\1\u0189\31\6\12\0"+
    "\2\6\4\0\25\6\1\u018a\5\6\12\0\2\6\4\0"+
    "\14\6\1\u018b\16\6\12\0\2\6\4\0\15\6\1\u018c"+
    "\15\6\12\0\2\6\4\0\17\6\1\u018d\13\6\12\0"+
    "\2\6\4\0\2\6\1\u018e\30\6\12\0\2\6\4\0"+
    "\11\6\1\u018f\21\6\12\0\2\6\4\0\23\6\1\u0190"+
    "\7\6\12\0\2\6\4\0\15\6\1\u0191\15\6\12\0"+
    "\2\6\4\0\15\6\1\u0192\15\6\12\0\2\6\4\0"+
    "\15\6\1\u0193\15\6\12\0\2\6\4\0\12\6\1\u0194"+
    "\20\6\12\0\2\6\4\0\12\6\1\u0195\20\6\12\0"+
    "\2\6\4\0\12\6\1\u0196\20\6\12\0\2\6\4\0"+
    "\1\u0197\32\6\12\0\2\6\4\0\14\6\1\u0198\16\6"+
    "\12\0\2\6\4\0\12\6\1\u0199\20\6\12\0\2\6"+
    "\4\0\1\u019a\32\6\12\0\2\6\4\0\15\6\1\u019b"+
    "\15\6\12\0\2\6\4\0\17\6\1\u019c\13\6\12\0"+
    "\2\6\4\0\1\6\1\u019d\31\6\12\0\2\6\4\0"+
    "\1\6\1\u019e\31\6\12\0\2\6\4\0\1\6\1\u019f"+
    "\31\6\12\0\2\6\4\0\14\6\1\u01a0\16\6\12\0"+
    "\2\6\4\0\14\6\1\u01a1\16\6\12\0\2\6\4\0"+
    "\12\6\1\u01a2\20\6\12\0\2\6\4\0\12\6\1\u01a3"+
    "\20\6\12\0\2\6\4\0\1\u01a4\32\6\12\0\2\6"+
    "\4\0\7\6\1\u01a5\23\6\12\0\2\6\4\0\1\6"+
    "\1\u01a6\31\6\12\0\2\6\4\0\7\6\1\u01a7\23\6"+
    "\12\0\2\6\4\0\11\6\1\u01a8\21\6\12\0\2\6"+
    "\4\0\1\u01a9\32\6\12\0\2\6\4\0\7\6\1\u01aa"+
    "\23\6\12\0\2\6\4\0\11\6\1\u01ab\21\6\12\0"+
    "\2\6\4\0\17\6\1\u01ac\13\6\12\0\2\6\4\0"+
    "\1\6\1\u01ad\31\6\12\0\2\6\4\0\12\6\1\u01ae"+
    "\20\6\12\0\2\6\4\0\20\6\1\u01af\12\6\12\0"+
    "\2\6\4\0\14\6\1\u01b0\16\6\12\0\2\6\4\0"+
    "\11\6\1\u01b1\21\6";

  private static int [] zzUnpackTrans() {
    int [] result = new int[15480];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\3\1\4\11\31\1\2\11\2\0\56\1"+
    "\2\0\1\11\2\0\1\1\1\11\2\0\66\1\1\0"+
    "\u011c\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[433];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  public _YangLexer() {
    this((java.io.Reader)null);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public _YangLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    int size = 0;
    for (int i = 0, length = packed.length(); i < length; i += 2) {
      size += packed.charAt(i);
    }
    char[] map = new char[size];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < packed.length()) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      {@code false}, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position {@code pos} from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + ZZ_CMAP(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return com.intellij.psi.TokenType.BAD_CHARACTER;
            } 
            // fall through
          case 76: break;
          case 2: 
            { return com.intellij.psi.TokenType.WHITE_SPACE;
            } 
            // fall through
          case 77: break;
          case 3: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_IDENTIFIER;
            } 
            // fall through
          case 78: break;
          case 4: 
            { return YangTypes.YANG_SEMICOLON;
            } 
            // fall through
          case 79: break;
          case 5: 
            { return YangTypes.YANG_PLUS;
            } 
            // fall through
          case 80: break;
          case 6: 
            { return YangTypes.YANG_LEFT_BRACE;
            } 
            // fall through
          case 81: break;
          case 7: 
            { return YangTypes.YANG_RIGHT_BRACE;
            } 
            // fall through
          case 82: break;
          case 8: 
            { return YangTypes.YANG_STRING_LITERAL;
            } 
            // fall through
          case 83: break;
          case 9: 
            { yybegin(YYINITIAL); return YangTypes.YANG_SEMICOLON;
            } 
            // fall through
          case 84: break;
          case 10: 
            { yybegin(YYINITIAL); return YangTypes.YANG_LEFT_BRACE;
            } 
            // fall through
          case 85: break;
          case 11: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_RPC_KEYWORD;
            } 
            // fall through
          case 86: break;
          case 12: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_BIT_KEYWORD;
            } 
            // fall through
          case 87: break;
          case 13: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_KEY_KEYWORD;
            } 
            // fall through
          case 88: break;
          case 14: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_MUST_KEYWORD;
            } 
            // fall through
          case 89: break;
          case 15: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_LEAF_KEYWORD;
            } 
            // fall through
          case 90: break;
          case 16: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_LIST_KEYWORD;
            } 
            // fall through
          case 91: break;
          case 17: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_USES_KEYWORD;
            } 
            // fall through
          case 92: break;
          case 18: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_ENUM_KEYWORD;
            } 
            // fall through
          case 93: break;
          case 19: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_TYPE_KEYWORD;
            } 
            // fall through
          case 94: break;
          case 20: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_BASE_KEYWORD;
            } 
            // fall through
          case 95: break;
          case 21: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_CASE_KEYWORD;
            } 
            // fall through
          case 96: break;
          case 22: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_PATH_KEYWORD;
            } 
            // fall through
          case 97: break;
          case 23: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_WHEN_KEYWORD;
            } 
            // fall through
          case 98: break;
          case 24: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_RANGE_KEYWORD;
            } 
            // fall through
          case 99: break;
          case 25: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_UNITS_KEYWORD;
            } 
            // fall through
          case 100: break;
          case 26: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_INPUT_KEYWORD;
            } 
            // fall through
          case 101: break;
          case 27: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_VALUE_KEYWORD;
            } 
            // fall through
          case 102: break;
          case 28: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_ANYXML_KEYWORD;
            } 
            // fall through
          case 103: break;
          case 29: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_MODULE_KEYWORD;
            } 
            // fall through
          case 104: break;
          case 30: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_LENGTH_KEYWORD;
            } 
            // fall through
          case 105: break;
          case 31: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_REFINE_KEYWORD;
            } 
            // fall through
          case 106: break;
          case 32: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_UNIQUE_KEYWORD;
            } 
            // fall through
          case 107: break;
          case 33: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_STATUS_KEYWORD;
            } 
            // fall through
          case 108: break;
          case 34: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_OUTPUT_KEYWORD;
            } 
            // fall through
          case 109: break;
          case 35: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_IMPORT_KEYWORD;
            } 
            // fall through
          case 110: break;
          case 36: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_CONFIG_KEYWORD;
            } 
            // fall through
          case 111: break;
          case 37: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_CHOICE_KEYWORD;
            } 
            // fall through
          case 112: break;
          case 38: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_PREFIX_KEYWORD;
            } 
            // fall through
          case 113: break;
          case 39: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_AUGMENT_KEYWORD;
            } 
            // fall through
          case 114: break;
          case 40: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_TYPEDEF_KEYWORD;
            } 
            // fall through
          case 115: break;
          case 41: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_INCLUDE_KEYWORD;
            } 
            // fall through
          case 116: break;
          case 42: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_CONTACT_KEYWORD;
            } 
            // fall through
          case 117: break;
          case 43: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_FEATURE_KEYWORD;
            } 
            // fall through
          case 118: break;
          case 44: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_DEFAULT_KEYWORD;
            } 
            // fall through
          case 119: break;
          case 45: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_DEVIATE_KEYWORD;
            } 
            // fall through
          case 120: break;
          case 46: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_PATTERN_KEYWORD;
            } 
            // fall through
          case 121: break;
          case 47: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_ARGUMENT_KEYWORD;
            } 
            // fall through
          case 122: break;
          case 48: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_REVISION_KEYWORD;
            } 
            // fall through
          case 123: break;
          case 49: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_GROUPING_KEYWORD;
            } 
            // fall through
          case 124: break;
          case 50: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_IDENTITY_KEYWORD;
            } 
            // fall through
          case 125: break;
          case 51: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_PRESENCE_KEYWORD;
            } 
            // fall through
          case 126: break;
          case 52: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_POSITION_KEYWORD;
            } 
            // fall through
          case 127: break;
          case 53: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_NAMESPACE_KEYWORD;
            } 
            // fall through
          case 128: break;
          case 54: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_MANDATORY_KEYWORD;
            } 
            // fall through
          case 129: break;
          case 55: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_LEAF_LIST_KEYWORD;
            } 
            // fall through
          case 130: break;
          case 56: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_REFERENCE_KEYWORD;
            } 
            // fall through
          case 131: break;
          case 57: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_EXTENSION_KEYWORD;
            } 
            // fall through
          case 132: break;
          case 58: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_SUBMODULE_KEYWORD;
            } 
            // fall through
          case 133: break;
          case 59: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_CONTAINER_KEYWORD;
            } 
            // fall through
          case 134: break;
          case 60: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_DEVIATION_KEYWORD;
            } 
            // fall through
          case 135: break;
          case 61: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_BELONGS_TO_KEYWORD;
            } 
            // fall through
          case 136: break;
          case 62: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_ORDERED_BY_KEYWORD;
            } 
            // fall through
          case 137: break;
          case 63: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_IF_FEATURE_KEYWORD;
            } 
            // fall through
          case 138: break;
          case 64: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_YIN_ELEMENT_KEYWORD;
            } 
            // fall through
          case 139: break;
          case 65: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_DESCRIPTION_KEYWORD;
            } 
            // fall through
          case 140: break;
          case 66: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_NOTIFICATION_KEYWORD;
            } 
            // fall through
          case 141: break;
          case 67: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_YANG_VERSION_KEYWORD;
            } 
            // fall through
          case 142: break;
          case 68: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_MAX_ELEMENTS_KEYWORD;
            } 
            // fall through
          case 143: break;
          case 69: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_MIN_ELEMENTS_KEYWORD;
            } 
            // fall through
          case 144: break;
          case 70: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_ORGANIZATION_KEYWORD;
            } 
            // fall through
          case 145: break;
          case 71: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_REVISION_DATE_KEYWORD;
            } 
            // fall through
          case 146: break;
          case 72: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_ERROR_APP_TAG_KEYWORD;
            } 
            // fall through
          case 147: break;
          case 73: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_ERROR_MESSAGE_KEYWORD;
            } 
            // fall through
          case 148: break;
          case 74: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_FRACTION_DIGITS_KEYWORD;
            } 
            // fall through
          case 149: break;
          case 75: 
            { yybegin(VALUE_MODE); return YangTypes.YANG_REQUIRE_INSTANCE_KEYWORD;
            } 
            // fall through
          case 150: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
